package blocker

/*
 * domains.go — Curated distraction domain list.
 *
 * CONCEPT: The MVP blocking strategy is "block known distractions."
 * Post-MVP will use firewall-level true allowlisting (pf/WFP).
 *
 * This list covers the major categories of digital distraction:
 * - Social media (the #1 offender)
 * - News/media sites
 * - Entertainment/streaming
 * - Shopping
 * - Forums/communities
 * - Gaming
 * - Messaging (web versions)
 * - Dating
 * - Sports
 * - Miscellaneous time sinks
 *
 * The list is intentionally broad. Any site the user actually NEEDS
 * goes in their workspace's allowed_sites and gets excluded from blocking.
 */

// DistractionDomains returns the curated list of ~500 distraction domains.
// These are blocked by default during a seal, unless allowed by the workspace.
func DistractionDomains() []string {
	return []string{
		// ── Social Media ──────────────────────────────
		"facebook.com",
		"instagram.com",
		"twitter.com",
		"x.com",
		"tiktok.com",
		"snapchat.com",
		"pinterest.com",
		"linkedin.com",
		"tumblr.com",
		"reddit.com",
		"old.reddit.com",
		"threads.net",
		"mastodon.social",
		"bsky.app",
		"bsky.social",
		"truthsocial.com",
		"minds.com",
		"gab.com",
		"parler.com",
		"gettr.com",
		"vk.com",
		"weibo.com",
		"wechat.com",
		"line.me",
		"myspace.com",
		"flickr.com",
		"500px.com",
		"deviantart.com",
		"pixiv.net",
		"livejournal.com",
		"xing.com",
		"clubhouse.com",

		// ── News & Media ─────────────────────────────
		"news.ycombinator.com",
		"cnn.com",
		"bbc.com",
		"bbc.co.uk",
		"foxnews.com",
		"nytimes.com",
		"washingtonpost.com",
		"theguardian.com",
		"reuters.com",
		"apnews.com",
		"nbcnews.com",
		"abcnews.go.com",
		"cbsnews.com",
		"msnbc.com",
		"usatoday.com",
		"huffpost.com",
		"buzzfeed.com",
		"buzzfeednews.com",
		"vice.com",
		"vox.com",
		"theatlantic.com",
		"slate.com",
		"salon.com",
		"dailymail.co.uk",
		"nypost.com",
		"politico.com",
		"thehill.com",
		"axios.com",
		"businessinsider.com",
		"insider.com",
		"bloomberg.com",
		"cnbc.com",
		"marketwatch.com",
		"finance.yahoo.com",
		"fool.com",
		"seekingalpha.com",
		"investing.com",
		"techcrunch.com",
		"theverge.com",
		"engadget.com",
		"arstechnica.com",
		"wired.com",
		"gizmodo.com",
		"mashable.com",
		"thedailybeast.com",
		"drudgereport.com",
		"breitbart.com",
		"newsmax.com",
		"oann.com",
		"aljazeera.com",
		"rt.com",
		"npr.org",
		"pbs.org",
		"news.google.com",
		"msn.com",
		"yahoo.com",
		"aol.com",

		// ── Entertainment & Streaming ─────────────────
		"youtube.com",
		"netflix.com",
		"hulu.com",
		"disneyplus.com",
		"hbomax.com",
		"max.com",
		"peacocktv.com",
		"paramountplus.com",
		"primevideo.com",
		"crunchyroll.com",
		"funimation.com",
		"twitch.tv",
		"dailymotion.com",
		"vimeo.com",
		"rumble.com",
		"bitchute.com",
		"odysee.com",
		"9gag.com",
		"imgur.com",
		"giphy.com",
		"tenor.com",
		"knowyourmeme.com",
		"ifunny.co",
		"funnyjunk.com",
		"ebaumsworld.com",
		"cracked.com",
		"theonion.com",
		"babylonbee.com",
		"spotify.com",
		"open.spotify.com",
		"music.apple.com",
		"soundcloud.com",
		"pandora.com",
		"deezer.com",
		"tidal.com",
		"bandcamp.com",
		"last.fm",
		"genius.com",
		"imdb.com",
		"rottentomatoes.com",
		"metacritic.com",
		"letterboxd.com",
		"goodreads.com",

		// ── Shopping ──────────────────────────────────
		"amazon.com",
		"ebay.com",
		"walmart.com",
		"target.com",
		"bestbuy.com",
		"etsy.com",
		"aliexpress.com",
		"wish.com",
		"shein.com",
		"temu.com",
		"wayfair.com",
		"overstock.com",
		"newegg.com",
		"zappos.com",
		"nordstrom.com",
		"macys.com",
		"costco.com",
		"samsclub.com",
		"homedepot.com",
		"lowes.com",
		"ikea.com",
		"asos.com",
		"zara.com",
		"hm.com",
		"uniqlo.com",
		"nike.com",
		"adidas.com",
		"stockx.com",
		"goat.com",
		"grailed.com",
		"poshmark.com",
		"mercari.com",
		"offerup.com",
		"craigslist.org",
		"facebook.com/marketplace",
		"slickdeals.net",
		"retailmenot.com",
		"honey.com",
		"camelcamelcamel.com",

		// ── Forums & Communities ──────────────────────
		"quora.com",
		"medium.com",
		"substack.com",
		"discord.com",
		"discordapp.com",
		"slack.com",
		"4chan.org",
		"4channel.org",
		"8kun.top",
		"kiwifarms.net",
		"somethingawful.com",
		"bodybuilding.com/forum",
		"resetera.com",
		"neogaf.com",
		"lemmy.world",
		"voat.co",
		"digg.com",
		"stumbleupon.com",
		"del.icio.us",
		"lobste.rs",
		"tildes.net",
		"metafilter.com",
		"boingboing.net",
		"slashdot.org",
		"fark.com",
		"producthunt.com",
		"indiehackers.com",
		"news.ycombinator.com",

		// ── Gaming ────────────────────────────────────
		"store.steampowered.com",
		"steampowered.com",
		"epicgames.com",
		"gog.com",
		"itch.io",
		"roblox.com",
		"minecraft.net",
		"ea.com",
		"ubisoft.com",
		"blizzard.com",
		"battle.net",
		"playstation.com",
		"xbox.com",
		"nintendo.com",
		"ign.com",
		"gamespot.com",
		"kotaku.com",
		"polygon.com",
		"pcgamer.com",
		"rockpapershotgun.com",
		"eurogamer.net",
		"escapistmagazine.com",
		"gamefaqs.gamespot.com",
		"howlongtobeat.com",
		"speedrun.com",
		"boardgamegeek.com",
		"chess.com",
		"lichess.org",
		"pogo.com",
		"miniclip.com",
		"kongregate.com",
		"newgrounds.com",
		"armor games.com",
		"coolmathgames.com",
		"iogames.space",
		"krunker.io",
		"slither.io",
		"agar.io",
		"wordle.com",

		// ── Messaging (web) ──────────────────────────
		"web.whatsapp.com",
		"messenger.com",
		"web.telegram.org",
		"telegram.org",
		"signal.org",
		"element.io",
		"riot.im",

		// ── Dating ────────────────────────────────────
		"tinder.com",
		"bumble.com",
		"hinge.co",
		"match.com",
		"okcupid.com",
		"pof.com",
		"eharmony.com",
		"zoosk.com",
		"coffeemeetsbagel.com",
		"happn.com",
		"grindr.com",

		// ── Sports ────────────────────────────────────
		"espn.com",
		"sports.yahoo.com",
		"bleacherreport.com",
		"cbssports.com",
		"foxsports.com",
		"nbcsports.com",
		"theathletic.com",
		"si.com",
		"sbnation.com",
		"deadspin.com",
		"barstoolsports.com",
		"nfl.com",
		"nba.com",
		"mlb.com",
		"nhl.com",
		"premierleague.com",
		"transfermarkt.com",
		"flashscore.com",
		"sofascore.com",
		"livescore.com",
		"draftkings.com",
		"fanduel.com",
		"betmgm.com",
		"pointsbet.com",
		"bovada.lv",
		"bet365.com",

		// ── Misc Time Sinks ──────────────────────────
		"wikipedia.org",
		"wikihow.com",
		"tvtropes.org",
		"ranker.com",
		"listverse.com",
		"boredpanda.com",
		"distractify.com",
		"upworthy.com",
		"mentalfloss.com",
		"atlasobscura.com",
		"interestingengineering.com",
		"popularmechanics.com",
		"howstuffworks.com",
		"snopes.com",
		"zillow.com",
		"realtor.com",
		"redfin.com",
		"trulia.com",
		"apartments.com",
		"yelp.com",
		"tripadvisor.com",
		"expedia.com",
		"kayak.com",
		"booking.com",
		"airbnb.com",
		"hotels.com",
		"skyscanner.com",
		"google.com/flights",
		"maps.google.com",

		// ── Productivity killers disguised as work ────
		"mail.google.com",
		"outlook.live.com",
		"outlook.office.com",
		"calendar.google.com",
		"drive.google.com",
		"docs.google.com",
		"notion.so",
		"trello.com",
		"asana.com",
		"monday.com",
		"clickup.com",
		"airtable.com",
		"basecamp.com",
		"jira.atlassian.com",
		"confluence.atlassian.com",
		"figma.com",

		// ── AI chat (when not part of workspace) ──────
		"chat.openai.com",
		"chatgpt.com",
		"bard.google.com",
		"gemini.google.com",
		"poe.com",
		"character.ai",
		"perplexity.ai",
		"you.com",
		"phind.com",

		// ── Adult content ─────────────────────────────
		"pornhub.com",
		"xvideos.com",
		"xnxx.com",
		"xhamster.com",
		"redtube.com",
		"youporn.com",
		"spankbang.com",
		"rule34.xxx",
		"e621.net",
		"nhentai.net",
		"hanime.tv",
		"onlyfans.com",

		// ── Crypto/stocks day trading ─────────────────
		"coinbase.com",
		"binance.com",
		"kraken.com",
		"coinmarketcap.com",
		"coingecko.com",
		"tradingview.com",
		"robinhood.com",
		"webull.com",
		"etrade.com",
		"schwab.com",
		"fidelity.com",
		"thinkorswim.com",
		"wallstreetbets.com",

		// ── Gossip/celebrity ──────────────────────────
		"tmz.com",
		"eonline.com",
		"usmagazine.com",
		"people.com",
		"pagesix.com",
		"justjared.com",
		"perezshilton.com",
		"celebitchy.com",
	}
}
