// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddException(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddException'](arg1, arg2, arg3);
}

export function AttemptUnlock(arg1) {
  return window['go']['main']['App']['AttemptUnlock'](arg1);
}

export function CompleteSession(arg1) {
  return window['go']['main']['App']['CompleteSession'](arg1);
}

export function CreateFromTemplate(arg1, arg2) {
  return window['go']['main']['App']['CreateFromTemplate'](arg1, arg2);
}

export function CreateWorkspace(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateWorkspace'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function ExportStatsJSON() {
  return window['go']['main']['App']['ExportStatsJSON']();
}

export function GetBlockedAttempts() {
  return window['go']['main']['App']['GetBlockedAttempts']();
}

export function GetCurrentSession() {
  return window['go']['main']['App']['GetCurrentSession']();
}

export function GetRecentSessions(arg1) {
  return window['go']['main']['App']['GetRecentSessions'](arg1);
}

export function GetStatsSummary() {
  return window['go']['main']['App']['GetStatsSummary']();
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function GetWorkspace(arg1) {
  return window['go']['main']['App']['GetWorkspace'](arg1);
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function SealWorkspace(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SealWorkspace'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateWorkspace(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateWorkspace'](arg1, arg2, arg3, arg4, arg5, arg6);
}
