// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';
import {blocker} from '../models';
import {session} from '../models';
import {stats} from '../models';

export function AddException(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AttemptUnlock(arg1:string):Promise<boolean>;

export function CompleteSession(arg1:string):Promise<void>;

export function CreateFromTemplate(arg1:string,arg2:string):Promise<workspace.Workspace>;

export function CreateWorkspace(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:string,arg5:string,arg6:string):Promise<workspace.Workspace>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function ExportStatsJSON():Promise<string>;

export function GetBlockedAttempts():Promise<Array<blocker.BlockedAttempt>>;

export function GetCurrentSession():Promise<session.Session>;

export function GetRecentSessions(arg1:number):Promise<Array<stats.Session>>;

export function GetStatsSummary():Promise<stats.Summary>;

export function GetTemplates():Promise<Array<workspace.Template>>;

export function GetWorkspace(arg1:string):Promise<workspace.Workspace>;

export function HideWindow():Promise<void>;

export function ListWorkspaces():Promise<Array<workspace.Workspace>>;

export function SealWorkspace(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<session.Session>;

export function UpdateWorkspace(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<string>,arg5:string,arg6:string):Promise<workspace.Workspace>;
